import { useEffect } from 'react'
import { Link } from 'react-router-dom'

const STYLES = `
@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500&family=Crimson+Pro:ital,wght@0,300;0,400;1,300;1,400&family=DM+Mono:wght@300;400&display=swap');

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
:root {
  --ink: #1E1C1E; --paper: #F0EBE8; --gold: #C49090; --gold-dim: #A87878;
  --text-dim: #C8B8B8; --text-faint: #A89898;
  --grain: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.08'/%3E%3C/svg%3E");
}
html, body { min-height: 100%; background: #1E1C1E; }
body { font-family: 'Crimson Pro', Georgia, serif; background: var(--ink); color: var(--paper); -webkit-font-smoothing: antialiased; }

.legal-page { min-height: 100vh; background: var(--ink); position: relative; }
.legal-page::before {
  content: '';
  position: fixed;
  inset: 0;
  background: radial-gradient(ellipse 70% 50% at 20% 20%, rgba(160,110,110,0.1) 0%, transparent 60%),
    radial-gradient(ellipse 50% 70% at 80% 80%, rgba(100,70,70,0.12) 0%, transparent 60%);
  pointer-events: none;
  z-index: 0;
}
.legal-page::after {
  content: '';
  position: fixed;
  inset: 0;
  background-image: var(--grain);
  opacity: 0.35;
  pointer-events: none;
  z-index: 0;
}
.legal-inner { position: relative; z-index: 1; max-width: 680px; margin: 0 auto; padding: 2.5rem 2rem 4rem; }
.legal-back { font-family: 'DM Mono', monospace; font-size: 0.56rem; letter-spacing: 0.12em; text-transform: uppercase; color: var(--text-faint); text-decoration: none; display: inline-block; margin-bottom: 2.5rem; transition: color 0.2s; }
.legal-back:hover { color: var(--gold); }
.legal-title { font-family: 'Cormorant Garamond', Georgia, serif; font-size: clamp(2rem, 5vw, 3rem); font-weight: 300; letter-spacing: 0.12em; color: var(--paper); margin-bottom: 0.5rem; }
.legal-updated { font-family: 'DM Mono', monospace; font-size: 0.56rem; letter-spacing: 0.15em; text-transform: uppercase; color: var(--gold-dim); margin-bottom: 2.5rem; }
.legal-section { margin-bottom: 1.75rem; }
.legal-section h2 { font-family: 'Cormorant Garamond', Georgia, serif; font-size: 1.35rem; font-weight: 400; color: var(--paper); margin-bottom: 0.5rem; }
.legal-section p, .legal-section li { font-size: 1.05rem; line-height: 1.85; color: var(--text-dim); }
.legal-section ul { list-style: none; padding: 0; margin-top: 0.35rem; }
.legal-section li { padding-left: 1.1rem; position: relative; margin-bottom: 0.35rem; }
.legal-section li::before { content: '—'; position: absolute; left: 0; color: var(--gold-dim); }
.legal-section a { color: var(--gold); text-decoration: underline; text-underline-offset: 2px; }
.legal-section a:hover { color: var(--paper); }
`

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By creating an account and using Override, you agree to these Terms. If you do not agree, please do not use the program.',
  },
  {
    title: '2. What Override Is',
    body: 'Override is a self-directed identity reconstruction program for personal reflection and identity rebuilding following heartbreak or divorce. It is not a mental health service, clinical program, or medical treatment.',
  },
  {
    title: '3. What Override Is Not',
    body: (
      <>
        Override is not a substitute for professional mental health support or medical advice. AI-generated reflections are for personal reflection only — not clinical advice or diagnosis. If you are in crisis or experiencing thoughts of self-harm, contact a qualified professional or visit{' '}
        <a href="https://findahelpline.com" target="_blank" rel="noopener noreferrer">findahelpline.com</a>{' '}
        immediately.
      </>
    ),
  },
  {
    title: '4. The AI Reflections',
    body: 'Reflections are generated by AI, not a human. They are thinking prompts only — not clinical advice. They may be imperfect or not suited to your circumstances.',
  },
  {
    title: '5. Your Content and Privacy',
    body: "You own your written content. Entries are stored securely and not shared except as described in our Privacy Policy. Your entries are processed by Anthropic's AI to generate reflections.",
  },
  {
    title: '6. Payment and Refunds',
    body: (
      <>
        Override is a one-time purchase giving lifetime access. Refunds available within 7 days if you have not completed more than one chapter. Contact{' '}
        <a href="mailto:hello@theoverride.app">hello@theoverride.app</a> to request a refund.
      </>
    ),
  },
  {
    title: '7. Acceptable Use',
    body: 'Do not share account access, copy or reverse engineer the program, use it unlawfully, or submit harmful content.',
  },
  {
    title: '8. Intellectual Property',
    body: 'All content and program structure are the intellectual property of the Override creator. No reproduction without written permission.',
  },
  {
    title: '9. Limitation of Liability',
    body: 'Override and its creator are not liable for indirect or consequential damages from use of the program. Use is at your own risk.',
  },
  {
    title: '10. Changes to These Terms',
    body: 'We may update these Terms at any time. Continued use constitutes acceptance. Material changes will be notified by email.',
  },
  {
    title: '11. Governing Law',
    body: 'These Terms are governed by the laws of Canada.',
  },
  {
    title: '12. Contact',
    body: <a href="mailto:hello@theoverride.app">hello@theoverride.app</a>,
  },
]

export default function Terms() {
  useEffect(() => {
    const style = document.createElement('style')
    style.textContent = STYLES
    document.head.appendChild(style)
    return () => document.head.removeChild(style)
  }, [])

  return (
    <div className="legal-page">
      <div className="legal-inner">
        <Link to="/" className="legal-back">← Back</Link>
        <h1 className="legal-title">TERMS OF SERVICE</h1>
        <p className="legal-updated">Last updated: May 2026</p>
        {SECTIONS.map((section) => (
          <section key={section.title} className="legal-section">
            <h2>{section.title}</h2>
            <p>{section.body}</p>
          </section>
        ))}
      </div>
    </div>
  )
}
